### ISSUE TITLE
进入游戏后需要重新获取焦点以移动视角

### ISSUE THREAD

**Issue by xtexx** [UnknownDomainGames/PanguEngine#89]
进入游戏后，无法移动视角，但是可以破坏方块，在切换窗口以重新获得焦点后可以正常移动视角

**Comment by mouse0w0** [comment]
在非主线程调用glfw导致的问题

```
"Netty Client Handler #1@6276" daemon prio=5 tid=0x2d nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.lwjgl.glfw.GLFW.glfwSetInputMode(GLFW.java:3245)
	  at engine.graphics.glfw.GLFWCursor.setCursorState(GLFWCursor.java:35)
	  at engine.graphics.display.Cursor.disableCursor(Cursor.java:17)
	  at engine.gui.EngineGUIManager.showInternal(EngineGUIManager.java:53)
	  at engine.gui.EngineGUIManager.close(EngineGUIManager.java:74)
	  at engine.enginemod.client.network.PreGamePacketHandler.onReceivingGameData(PreGamePacketHandler.java:57)
	  at AsmDynamicListener_5793b87_PreGamePacketHandler_onReceivingGameData_PacketReceivedEvent_10.post(.dynamic:-1)
	  at engine.event.misc.RegisteredListener.post(RegisteredListener.java:63)
	  at engine.event.SimpleEventBus.post(SimpleEventBus.java:35)
	  at engine.server.network.NetworkHandler.channelRead0(NetworkHandler.java:135)
	  at engine.server.network.NetworkHandler.channelRead0(NetworkHandler.java:28)
	  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	  at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
	  at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
	  at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
	  at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
	  at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	  at java.lang.Thread.run(Thread.java:834)

```
